version: '3.8'
services:

  db:
    image: postgres:15-alpine
    container_name: cultura-database
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: newdbav5
      POSTGRES_DB: cultura-radio
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - traefik-public

  app:
    build: .
    container_name: cultura-api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://root:newdbav5@db:5432/cultura-radio"
      PORT: "5000"

    labels:
      - traefik.enable=true

      - traefik.http.routers.projectCultura-http.rule=Host(`radio-cultura.cgmcloud.com.br`)
      - traefik.http.routers.projectCultura-http.entrypoints=http
      - traefik.http.routers.projectCultura-http.middlewares=https-redirect

      - traefik.http.routers.projectCultura-https.rule=Host(`radio-cultura.cgmcloud.com.br`)
      - traefik.http.routers.projectCultura-https.entrypoints=https
      - traefik.http.routers.projectCultura-https.tls=true
      - traefik.http.routers.projectCultura-https.tls.certresolver=le
      - traefik.http.routers.projectCultura-https.service=projectCultura-service
      - traefik.http.services.projectCultura-service.loadbalancer.server.port=5000
    networks:
      - traefik-public
    ports:
      - "5000:5000"
    volumes:
      # Mount everything except .env file
      - ./prisma:/app/prisma:cached
      - ./src:/app/src:cached
      - ./package.json:/app/package.json:cached
      - ./package-lock.json:/app/package-lock.json:cached
      - ./tsconfig.json:/app/tsconfig.json:cached
      - /app/node_modules
    command: npm run start

volumes:
  pg_data:


networks:
  traefik-public:
    external: true
